/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    asset: Asset;
    users: User;
    companies: Company;
    vacancies: Vacancy;
    assessments: Assessment;
    assessmentSubmissions: AssessmentSubmission;
    vacancySubmissions: VacancySubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    asset: AssetSelect<false> | AssetSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    vacancies: VacanciesSelect<false> | VacanciesSelect<true>;
    assessments: AssessmentsSelect<false> | AssessmentsSelect<true>;
    assessmentSubmissions: AssessmentSubmissionsSelect<false> | AssessmentSubmissionsSelect<true>;
    vacancySubmissions: VacancySubmissionsSelect<false> | VacancySubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset".
 */
export interface Asset {
  id: number;
  alt?: string | null;
  author?: (number | null) | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'company' | 'candidate') | null;
  avatar?: (number | null) | Asset;
  phone?: string | null;
  gender?: ('male' | 'female') | null;
  education?: ('bachelor' | 'master' | 'diploma' | 'highSchool' | 'middleSchool' | 'elementarySchool') | null;
  biography?: string | null;
  resume?: (number | null) | Asset;
  documents?: (number | Asset)[] | null;
  socials?: {
    website?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  logo?: (number | null) | Asset;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  businessCategory?: string | null;
  location?: string | null;
  totalEmployees?: number | null;
  socials?: {
    website?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
  };
  gallery?: (number | Asset)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Asset;
  };
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Asset;
  favicon?: (number | null) | Asset;
  publishedAt?: string | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies".
 */
export interface Vacancy {
  id: number;
  type?: ('fullTime' | 'partTime' | 'contract' | 'internship') | null;
  level?: ('senior' | 'medior' | 'junior') | null;
  education?: ('bachelor' | 'master' | 'diploma' | 'highSchool' | 'middleSchool' | 'elementarySchool') | null;
  fromExpectedSalary?: number | null;
  toExpectedSalary?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Asset;
  };
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Asset;
  company: number | Company;
  expiresAt?: string | null;
  closeVacancy?: boolean | null;
  publishedAt?: string | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments".
 */
export interface Assessment {
  id: number;
  /**
   * In minutes
   */
  duration?: number | null;
  /**
   * In percentage
   */
  passingGrade?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  questions?:
    | {
        question?: string | null;
        /**
         * Please use this only as a helper for the question, not as the main question, because this feature is not supported yet if you treat as main question.
         */
        questionMedia?: (number | null) | Asset;
        /**
         * Please make sure to include answer options, and fill the "expected answer" field with the correct answer selected from those options.
         */
        isAnswerOptions?: boolean | null;
        answerOptions?:
          | {
              answerOption?: string | null;
              id?: string | null;
            }[]
          | null;
        expectedAnswer?: string | null;
        id?: string | null;
      }[]
    | null;
  title: string;
  slug: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Asset;
  vacancy?: (number | null) | Vacancy;
  publishedAt?: string | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessmentSubmissions".
 */
export interface AssessmentSubmission {
  id: number;
  candidateName: string;
  candidate?: {
    avatar?: (number | null) | Asset;
    phone?: string | null;
    gender?: ('male' | 'female') | null;
    education?: ('bachelor' | 'master' | 'diploma' | 'highSchool' | 'middleSchool' | 'elementarySchool') | null;
    biography?: string | null;
    resume?: (number | null) | Asset;
    documents?: (number | Asset)[] | null;
    socials?: {
      website?: string | null;
      facebook?: string | null;
      instagram?: string | null;
      linkedin?: string | null;
      twitter?: string | null;
      youtube?: string | null;
      tiktok?: string | null;
    };
  };
  userCandidateCompany: (number | User)[];
  score: number;
  assessment?: (number | null) | Assessment;
  summary?: string | null;
  assessmentResults?:
    | {
        isAnswerCorrect?: boolean | null;
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancySubmissions".
 */
export interface VacancySubmission {
  id: number;
  candidateName: string;
  candidate?: {
    avatar?: (number | null) | Asset;
    phone?: string | null;
    gender?: ('male' | 'female') | null;
    education?: ('bachelor' | 'master' | 'diploma' | 'highSchool' | 'middleSchool' | 'elementarySchool') | null;
    biography?: string | null;
    resume?: (number | null) | Asset;
    documents?: (number | Asset)[] | null;
    socials?: {
      website?: string | null;
      facebook?: string | null;
      instagram?: string | null;
      linkedin?: string | null;
      twitter?: string | null;
      youtube?: string | null;
      tiktok?: string | null;
    };
  };
  userCandidateCompany: (number | User)[];
  vacancy?: {
    type?: ('fullTime' | 'partTime' | 'contract' | 'internship') | null;
    level?: ('senior' | 'medior' | 'junior') | null;
    education?: ('bachelor' | 'master' | 'diploma' | 'highSchool' | 'middleSchool' | 'elementarySchool') | null;
    fromExpectedSalary?: number | null;
    toExpectedSalary?: number | null;
  };
  vacancyReference?: (number | null) | Vacancy;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'asset';
        value: number | Asset;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'vacancies';
        value: number | Vacancy;
      } | null)
    | ({
        relationTo: 'assessments';
        value: number | Assessment;
      } | null)
    | ({
        relationTo: 'assessmentSubmissions';
        value: number | AssessmentSubmission;
      } | null)
    | ({
        relationTo: 'vacancySubmissions';
        value: number | VacancySubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset_select".
 */
export interface AssetSelect<T extends boolean = true> {
  alt?: T;
  author?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  phone?: T;
  gender?: T;
  education?: T;
  biography?: T;
  resume?: T;
  documents?: T;
  socials?:
    | T
    | {
        website?: T;
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        youtube?: T;
        tiktok?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  businessCategory?: T;
  location?: T;
  totalEmployees?: T;
  socials?:
    | T
    | {
        website?: T;
        facebook?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        youtube?: T;
        tiktok?: T;
      };
  gallery?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  favicon?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies_select".
 */
export interface VacanciesSelect<T extends boolean = true> {
  type?: T;
  level?: T;
  education?: T;
  fromExpectedSalary?: T;
  toExpectedSalary?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  company?: T;
  expiresAt?: T;
  closeVacancy?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments_select".
 */
export interface AssessmentsSelect<T extends boolean = true> {
  duration?: T;
  passingGrade?: T;
  description?: T;
  questions?:
    | T
    | {
        question?: T;
        questionMedia?: T;
        isAnswerOptions?: T;
        answerOptions?:
          | T
          | {
              answerOption?: T;
              id?: T;
            };
        expectedAnswer?: T;
        id?: T;
      };
  title?: T;
  slug?: T;
  excerpt?: T;
  featuredImage?: T;
  vacancy?: T;
  publishedAt?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessmentSubmissions_select".
 */
export interface AssessmentSubmissionsSelect<T extends boolean = true> {
  candidateName?: T;
  candidate?:
    | T
    | {
        avatar?: T;
        phone?: T;
        gender?: T;
        education?: T;
        biography?: T;
        resume?: T;
        documents?: T;
        socials?:
          | T
          | {
              website?: T;
              facebook?: T;
              instagram?: T;
              linkedin?: T;
              twitter?: T;
              youtube?: T;
              tiktok?: T;
            };
      };
  userCandidateCompany?: T;
  score?: T;
  assessment?: T;
  summary?: T;
  assessmentResults?:
    | T
    | {
        isAnswerCorrect?: T;
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancySubmissions_select".
 */
export interface VacancySubmissionsSelect<T extends boolean = true> {
  candidateName?: T;
  candidate?:
    | T
    | {
        avatar?: T;
        phone?: T;
        gender?: T;
        education?: T;
        biography?: T;
        resume?: T;
        documents?: T;
        socials?:
          | T
          | {
              website?: T;
              facebook?: T;
              instagram?: T;
              linkedin?: T;
              twitter?: T;
              youtube?: T;
              tiktok?: T;
            };
      };
  userCandidateCompany?: T;
  vacancy?:
    | T
    | {
        type?: T;
        level?: T;
        education?: T;
        fromExpectedSalary?: T;
        toExpectedSalary?: T;
      };
  vacancyReference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}